apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-player-app
  template:
    metadata:
      labels:
        app: music-player-app
    spec:
      containers:
        - name: music-player-app
          image: jattin11/music-player:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
